### ISSUE TITLE
URL with a trailing `.` does not load

### ISSUE THREAD

**Issue by Levi-Lesches** [schej-it/schej.it#100]
Eg: 
- `https://schej.it/e/b9fB9` -- works
- `https://schej.it/e/b9fB9.` -- does not work

This can happen by accident when sending someone the link. Would be nice if the trailing `.` was removed automatically

**Comment by jonyTF** [comment]
Hi! Thanks for the feedback.

How did this happen? Did you paste the link in a chat and have the imessage auto-period thing enabled?

**Comment by Levi-Lesches** [comment]
Pasted the link at the end of a sentence, so I put the sentence in, but discord's auto-link mechanism captures the period as well :(

**Comment by jonyTF** [comment]
Oh nooo yeah that sounds annoying. Periods will never be included in the ID so sounds like it would be safe to trim. 

Feel free to open a PR in the Vue version (we haven't touched the flutter app in over 2 years LOL), lmk if you have any trouble or if you prefer that I do it instead.
