### ISSUE TITLE
Website down - 502 Bad Gateway

### ISSUE THREAD

**Issue by jdmedlock** [schej-it/schej.it#104]
When accessing the website, https://schej.it/home, the page that's displayed is a 502 Bad Gateway. The site appears to be down.

I'm using the Brave browser (
Version 1.69.162 Chromium: 128.0.6613.120 (Official Build) (x86_64) ) on a MacOS Monterey 12.7.6

![image](https://github.com/user-attachments/assets/e14fadef-df99-47ac-aa94-99c29f2da1dc)

**Comment by joshuahertz** [comment]
Glad I'm not the only one. Using chrome on windows, trying to access a schej that was working yesterday.

**Comment by jonyTF** [comment]
So sorry about that! Our server crashed overnight, but it should be back up now :)
