### ISSUE TITLE
[Feature Request] Allow integration from other calendars within external Google account

### ISSUE THREAD

**Issue by MMachado05** [schej-it/schej.it#106]
When adding a new google account that differs from the one you used to open your account, Schej only takes your availability from the calendar directly associated with that google account, meaning other calendars created by the user (i.e. specialized calendars made for organizational purposes such as "Classes" or "Chores") are ignored. My use case is that I have a sub-calendar in my account specifically for my university lectures that belongs to a personal email I only use *for* emails, which is different from the one that I used to sign up. Because these lectures are held in a calendar that *isn't* the primary calendar in an added account, they aren't being detected by Schej, meaning they don't get added to my availability.

**Comment by jonyTF** [comment]
Hi! If you click on the dropdown next to your calendar, you should be able to toggle which sub-calendars are visible. Let us know if that works for you :)

<img width="263" alt="image" src="https://github.com/user-attachments/assets/d6e0c4a3-051f-4101-814f-a3ab39f378d7">

**Comment by MMachado05** [comment]
Shoot, you're right! I didn't realize that's what the arrow was for. Thank you so much!

Maybe that could be something that says "view more calendars"? Though at this point, that's getting rather subjective. 😅 Thanks again!
