### ISSUE TITLE
Emails are case sensitive and it breaks access if you entered an email with an uppercase letter in attendees. 

### ISSUE THREAD

**Issue by RustyRaptor** [schej-it/schej.it#109]
I guess we just need to convert the emails to lowercase in this if statement or fix it when adding attendees. This can be a common issue because a lot of mobile autocorrect systems will capitalize first letter of emails when you type them. 

https://github.com/schej-it/schej.it/blob/35df73649a6cc3cbaf44482d5f7434d677d67648/frontend/src/views/Group.vue#L57

I'm the same person who sent the feedback report about this. So, I guess this is me confirming that the issue was indeed case sensitivity.

**Comment by jonyTF** [comment]
Awesome! Thanks for making the pull request :)
