### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by elbrand22** [schej-it/schej.it#111]
I cannot access my calendar anymore and am getting a 502 error, but it's already filled out so I really need to get access to it!!

https://schej.it/e/9bF39

nginx/1.14.0 (Ubuntu)

**Comment by DominikStiller** [comment]
I am also getting 502 Bad Gateway when trying to create a new event.

**Comment by mafiefa02** [comment]
It looked like the server is down, cause I'm also getting a 502 response

**Comment by liurm97** [comment]
Same here. Getting 502 bad gateway when trying to create a new event.

**Comment by jonyTF** [comment]
So sorry our server crashed, the website should be back up now!
