### ISSUE TITLE
Dates not matching days

### ISSUE THREAD

**Issue by jsendlewski** [schej-it/schej.it#121]
It seems that the day names are not matching the actual dates in calendar. It looks like days got shifted by 1d. 

Here you can see that 1st of Nov 2024 is Saturday - according to Schej calendar.
![issue_sch](https://github.com/user-attachments/assets/317936cd-2799-40f2-9d1f-edf02e41b9b4)

It should be Friday: 
![image](https://github.com/user-attachments/assets/8046e5f8-27b4-4d7e-980b-cd08faa9047b)

Note: It appears that the issue happens only in "dates and times" calendar. "Dates only" mode seems to be okay.

**Comment by jonyTF** [comment]
Hi, we have had several people report this in the past but for some reason it's impossible for us to reproduce it. However, some people have had this bug go away when using different browsers

**Comment by jsendlewski** [comment]
That's interesting, I'll experiment a bit with - just as you said - different browsers. Will try to check the actual behaviour and it's root cause. If I manage to find something and have enough time (most likely next weekend) I'll prepare some PR with fix

**Comment by jsendlewski** [comment]
Ok, I did some quick tests. Enabling incognito mode indeed fixed the problem - therefore my thinking was that it's either something in cookies causing an issue or local storage. After quick look into local storage and deleting variable connected to start week on Monday the issue was fixed:
![image](https://github.com/user-attachments/assets/6dc3e1e7-aceb-4848-b803-bfe6dcf321f6)

**Comment by jonyTF** [comment]
Ahhhh ok very interesting thanks for discovering this! Must be some error in the logic of us adding the startOnMonday flag, will fix if I have time this weekend

**Comment by jonyTF** [comment]
Okay just deployed a quick fix that gets rid of this flag for now! 

68010db6a9b05ee1224a339182be921a70608784
