### ISSUE TITLE
Site stuck on load - blank screen

### ISSUE THREAD

**Issue by raviriley** [schej-it/schej.it#37]
Site isn't loading, hangs up on "Waiting for www.gstatic.com" which could be a google fonts issue?

<img width="1493" alt="image" src="https://github.com/schej-it/schej.it/assets/8132955/392d6957-9fd5-4873-b990-7bab564cd0ce">

The boxed request never completes. 

Eventually, get a TypeError in the console:

<img width="1454" alt="image" src="https://github.com/schej-it/schej.it/assets/8132955/5f84a998-25b8-4dff-a0ad-07740f25af55">

On Chromium / Chrome browsers (Arc, Brave, Chrome) reproduced with metadata page load with blank screen, but on Safari the site simply never loads.

**Comment by jonyTF** [comment]
Oh shoot this is very bad, I will look into what is happening

**Comment by jonyTF** [comment]
Update on this, I pointed the domain name to a new ip address, so it should be back up once that domain change propagates...

**Comment by jonyTF** [comment]
@raviriley Website is back up!

**Comment by raviriley** [comment]
Hype
