### ISSUE TITLE
Change "available" color grades to avoid ambiguous best availability

### ISSUE THREAD

**Issue by MMachado05** [schej-it/schej.it#94]
The deep green hue used for the "best" available times is applied to when the most people are available; this doesn't always mean *all* people are available. I've just recently had a meeting where a good few blocks were filled out in the deep green color, but hovering over the times in particular, I noticed only 3 of the 4 members were free during those times. The rich color used to fill these blocks in was a bit misleading, and as a result, I ended up scheduling a meeting not all of us were able to attend.

I think it would be best to reserve this deep green color exclusively for times that *all* respondents of the Schej can attend. In addition (or substitution), there could be a note at the bottom of the calendar table that says something such as,

> There are no times in these dates where all attendants are available at once.

I'm sure there's a better way to phrase it, but I hope the idea I'm communicating is clear.

**Comment by jonyTF** [comment]
Hi, appreciate the feedback! 

So sorry that the dark green was a bit misleading, we will implement this change ASAP :)

**Comment by jonyTF** [comment]
Just deployed this feature! 

Overlapping times where not everybody is available is now a lighter shade of green and there is a note at the bottom clarifying that there is no time where everybody is available
![image](https://github.com/user-attachments/assets/e7ecd626-aa09-4a7d-8609-b1284ada1f37)

**Comment by MMachado05** [comment]
Should I be doing anything in particular to be seeing this? I made a test availability to see this feature in action, but the "best" times that don't include everyone are still a deep green, and there's no note at the bottom.
![image](https://github.com/user-attachments/assets/6c900c18-93fe-4e9f-ae77-6541af0c3a7e)
As a note, the large chunks are me, and the one hour bit on the first day is Test.

**Comment by jonyTF** [comment]
Hi,

In order to see the changes you may need to force refresh the page with (cmd+shift+r)

Let me know if that fixes it!

**Comment by MMachado05** [comment]
That it does! I must have had the tab open from a prior session.

One last suggestion I might make: Selecting the "Show Best Times" toggle button will, naturally, still only show the ideal times, which don't include all respondents. Maybe there could be some warning in some way when this is clicked to make sure the user knows that best times != all-available times? Potentially even as an alternative to the note? Just a minor thought! The current system certainly works. 😁
